"""Compatibility imports for the old Qt runtime bridge location."""

from uvr.runtime import (
    BASE_PATH,
    DEMUCS_MODEL_NAME_SELECT,
    DEMUCS_MODELS_DIR,
    DEMUCS_NEWER_REPO_DIR,
    DENOISER_MODEL_PATH,
    DEVERBER_MODEL_PATH,
    MDX_C_CONFIG_PATH,
    MDX_HASH_DIR,
    MDX_HASH_JSON,
    MDX_MIXER_PATH,
    MDX_MODEL_NAME_SELECT,
    MDX_MODELS_DIR,
    MODELS_DIR,
    VR_HASH_DIR,
    VR_HASH_JSON,
    VR_MODELS_DIR,
    VR_PARAM_DIR,
    configure_backend_runtime,
    create_runtime,
    discover_models,
    load_json,
    read_model_catalog,
)
